services:
  nginx:
    build: ".docker/local/nginx"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: ".docker/local/php"
    container_name: app
    working_dir: /app
    volumes:
      - ".:/app"
      - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "5173:5173"
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
      - OS_NAME
    depends_on:
      - mysql
      - redis
      - minio
      - mailpit
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue_worker:
    build: ".docker/local/php"
    container_name: queue-worker
    working_dir: "/app"
    command: "php artisan queue:work --tries=3 --queue=high,default,low"
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
      - OS_NAME
    volumes:
      - ".:/app"
      - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - mysql
      - redis
      - minio
      - mailpit
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: mysql
    platform: linux/amd64
    build: ".docker/local/mysql"
    ports:
      - "3306:3306"
    volumes:
      - ".docker/local/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./storage/mysql:/var/lib/mysql"
      - ".docker/local/mysql/mysql-docker-entrypoint.sql:/docker-entrypoint-initdb.d/mysql-docker-entrypoint.sql"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:6.2-buster
    container_name: redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9001 --console-address :9002"

  minio_client:
    container_name: create-bucket
    image: minio/mc
    entrypoint: [ "" ]
    command:
      - /bin/sh
      - -c
      - |
        until (mc config host add minio http://minio:9001 access_key secret_key) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/public
        mc policy set public minio/public
        mc mb minio/private
        mc policy set private minio/private
        mc mb minio/uploads
        mc policy set private minio/uploads
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    depends_on:
      - minio

  elasticmq:
    container_name: elasticmq
    image: softwaremill/elasticmq-native:1.2.0
    volumes:
      - ./.docker/local/elasticmq/custom.conf://opt/elasticmq.conf:ro
    ports:
      - "9324:9324"
      - "9325:9325"
